### ISSUE TITLE
congrats on Seq4

### ISSUE THREAD

**Issue by XtremeSounds** [jeremymuller/Sha-Bang-Modules#11]
Now thats what Im talking about.  I guess its probability on each note?  Not a note for note sequencer correct?  

can you make a non probability sequencer like this? Does it come in black?

**Comment by jeremymuller** [comment]
The gates are only triggered based on the probability set by the sliders, i.e. so a halfway slider would be a 50% chance the gate will occur. The `V/OCT` doesn't correspond to probability, they just output volts like a typical sequencer. 

What exactly would you want a non probability sequencer like this to be? I'm not quite sure I understand what you're asking. I have thought about making extra skins for my modules, like a dark mode or something, however I'm currently working on adding several modules to the next version update, as well as other bug fixes, etc. So it may be a while before I add some cosmetic changes.

**Comment by XtremeSounds** [comment]
Good question. I originally thought it was a normal 4 track sequencer but I think it does something a little differently as the name implies. I thought the sliders are controlling the pitch but there is a probability element to it as well.   It is cool though.  Ill keep playing around with it as its very useful.

**Comment by jeremymuller** [comment]
Yeah, sliders do control pitch, so if you want to skip the probability part of it you can just have the clock control your envelope as well. I'll be making some tutorial videos on these modules soon.

**Comment by XtremeSounds** [comment]
Ok thanks

**Comment by jeremymuller** [comment]
I'm going to close this issue for now. Adding a dark mode skin will be something I'll consider after I get some other work out of the way.
