### ISSUE TITLE
Neutrinode stops playing off screen

### ISSUE THREAD

**Issue by jeremymuller** [jeremymuller/Sha-Bang-Modules#22]
No it's Neutrinode in my case it just closed rack.
It also stops playing when you move the module out of frame.
like this : 
![afbeelding](https://user-images.githubusercontent.com/46076474/109535807-4467e800-7abd-11eb-8970-6e3245c16f0b.png)

Here is the patch ( It includes both modules... so I'm not sure who's to blame ;( )

[Neutro and Orbi - 01032021.zip](https://github.com/jeremymuller/Sha-Bang-Modules/files/6063406/Neutro.and.Orbi.-.01032021.zip)

_Originally posted by @Petervos2018 in https://github.com/jeremymuller/Sha-Bang-Modules/issues/21#issuecomment-788136974_

**Comment by jeremymuller** [comment]
https://github.com/jeremymuller/Sha-Bang-Modules/issues/21#issuecomment-788176159

**Comment by jeremymuller** [comment]
Ok, I'm pretty sure I've found the problem with Neutrinode not playing off screen. And I also think this bug could potentially cause a crash. I'll fix this and the other issue and send out the update ASAP.

**Comment by Petervos2018** [comment]
First test of the new build look promising, it keeps playing off screen, and no crash yet.
Thank you Jeremy.

**Comment by jeremymuller** [comment]
Everything still good? I'm going to close this issue but if you experience problems with it again just comment here.
