### ISSUE TITLE
Move function on Neutrinode is not saved with the patch

### ISSUE THREAD

**Issue by omricohenmusic** [jeremymuller/Sha-Bang-Modules#28]
Hi Jeremy!
I noticed that when I save a patch with Neutrinode, and I have the Move function on, the next time I open the patch, I have to enable it again. Is there a way to have it save the status of the Move function so it will be enabled when opening a patch?
Thanks again!

**Comment by jeremymuller** [comment]
@omricohenmusic Ok no problem, looks like I just forgot to add that in there.

**Comment by omricohenmusic** [comment]
Thanks so much!
