### ISSUE TITLE
StochSeq4 feedback & feature request

### ISSUE THREAD

**Issue by S0210** [jeremymuller/Sha-Bang-Modules#29]
Dear Jeremy,

Your StochSeq4 is the best sequencer in the VCV world. It's as simple as that. There are prettier ones but its functionality, efficiency, and practicality is unmatched.  

But if you ever decide to re-visit the code I'd like to ask you to consider a few changes
- keyboard shortcut: Ctrl-Tab to focus the independent patterns one by one
- keyboard shortcut: Ctrl-Left & Ctrl-Right to shift all steps of focused pattern to the left/right by one step
- keyboard shortcut: Ctrl-Up & Ctrl-Down to increase/decrease all probabilities of a focused pattern by 5
- new output: inverted V/OCT for each pattern
- new output: NOT GATE for each pattern
- new output: a single OR GATES output (next to the scale knobs) 
- new output: a single XOR GATES output (next to the scale knobs) 
- macro feature: store the predefined preset patterns in a separate JSON/TXT file

With or without these changes your sequencer remains absolutely brilliant. Thank you for this wonderful module!

Best regards, Andras

**Comment by jeremymuller** [comment]
Hi Andras, thank you for your comments. I'm so glad you like this module. And since I am interested in a visual aesthetic I would be curious about how I could make it more appealing in terms of its interface. Do you have some examples of beautiful modules in mind?

Also, I like all these features you mentioned. I value good input like this so I can improve these modules. I'll definitely try to implement them in the next update. I was working on a new version of ShaBang modules but have been busy in the past few months so I've been unable to work on it. I'll try and get to it soon.

**Comment by S0210** [comment]
Hi Jeremy,

I'm afraid my input is not much of a help from visual point of view. But in general I'm in favour of the clean scientific design (like Doepfer or Impromptu, Count Modula). I do appreciate big buttons and multiple available skin options (dark/light) always having something bright as my default. My absolute favourite module design is SuperCell with it's huge faceplace, logical arrangement and big spaces around the most used knobs. (To be fair it's not among my most used modules otherwise.)

The real challenging design part in case of StochSeq4 is the set of sliders. I think it's wonderfully implemented as is. Easy to work with them and they give a good visual feedback what can be expected. Another good example of this concept is CodeFN42 CCstepper:  https://www.codefn42.com/ccstepper/ It is a MIDI CC generation VST module but the slider width is dynamically changing in line with the pattern length.

Feeling encouraged by your words I'd like to draw you attention to the extension modules. I think StochSeq4 could also benefit from them. This proposal would incorporate the previously suggested keyboard features (shift & increase) in a more traditional way. Additionally it could have 32 GATE outputs (as seen in StochSeq1). Please note the track knob that allows selection only one of the four tracks of StochSeq4. 

<img width="171" alt="StochSeq4 extension proposal A" src="https://user-images.githubusercontent.com/34127628/129846664-14ade36f-2937-4968-8d86-223842893a59.png">

I'm also thinking about a live performance related expansion. What is the direction of your work on new versions? Is it linked somehow to any of your coming live performances?

Best regards, Andras

**Comment by jeremymuller** [comment]
Thanks, Andras. This gives me a lot to consider. I won't be able to really work on it for a while since I'm preparing for some upcoming performances at the moment. 

I had started working on a new module several months ago. Once I have time to work on it again I'll definitely try to implement the ideas you mentioned here.

**Comment by S0210** [comment]
Dear Jeremy,

Please let me share a possible implementation for one of the requests above:
* macro feature: store the predefined preset patterns in a separate JSON/TXT file

StochSeq4 PATT knobs could loop through respective tracks of 'Factory presets' of the context menu. These are regular .vcvm files saved  in a default folder (like ..\Documents\Rack\plugins-v1\Sha-Bang-Modules\presets\StochSeq4 ). 

Working example if factoryA.vcvm, factoryB.vcvm, factoryC.vcvm are save in the default folder:
* turning PATT#1 would load track#1 of factoryA.vcvm (track#2 is unchanged)
* turning PATT#1 would load track#1 of factoryB.vcvm (track#2 is unchanged)
* turning PATT#2 would load track#2 of factoryA.vcvm (track#1 is unchanged)
* turning PATT#1 would load track#1 of factoryC.vcvm (track#2 is unchanged)

Something like that. I'm not aware of the technical challenges this solution might bring but I find it a very nice and flexible way of using the default VCV features. 

Best regards, Andras

**Comment by jeremymuller** [comment]
Ok, I have seen some other modules store  preset .vcvm files as well. I'll think about how to implement this. As for now, there are factory presets built into the module (not as separate files, though). And it will save whatever slider values you currently have...if you want to copy them you can duplicate the module and the same slider values will be loaded.

**Comment by jeremymuller** [comment]
@S0210 there's a new update coming with Sha#Bang! and I've implemented some keyboard shortcuts and variable width sliders. I also have NOT gates, INV, and OR/XOR. In StochSeq4 you can cycle through each pattern with CTRL+Enter and even copy/paste patterns and their lengths into other ones with CTRL+C or CTRL+V. After I migrate to Rack v2 I'll work on an expander for StochSeq4 and the pattern presets stored as JSON.

**Comment by S0210** [comment]
First reaction: Ctrl-Enter is extremely useful. Keyboard shortcuts are very handy in general. 
Relocation of sockets (inc. INV, NOT) works unexpectedly well. Having a single glance I see all the options I can play with. It's strange what a great difference it makes. 
I see that you also managed to redraw the sliders according to the LEN settings. 
Wow, it is a first class update indeed! I'll spend some more time with it later.
Congrats!

**Comment by S0210** [comment]
I managed to set the probability to -1 with mouse somehow. Minor issue. No crash or anything...
![image](https://user-images.githubusercontent.com/34127628/135597671-ab112c8f-2119-45d4-ae8a-1fcd76ddf18f.png)
![image](https://user-images.githubusercontent.com/34127628/135597891-b8d6ef05-3484-40f4-8814-96b026d1a1e7.png)

**Comment by S0210** [comment]
Is the gate PW independent from the incoming clock signal? Is it fixed? 
![image](https://user-images.githubusercontent.com/34127628/135601171-3a747bbe-1516-4745-adeb-24a46df64d98.png)

At a moderately high clock speed I see that 'pulses touch each other'. 
![image](https://user-images.githubusercontent.com/34127628/135601275-197e2d57-9344-493c-a08a-d9b50807c974.png)

**Comment by jeremymuller** [comment]
> I managed to set the probability to -1 with mouse somehow. Minor issue. No crash or anything...
> 
> ![image](https://user-images.githubusercontent.com/34127628/135597671-ab112c8f-2119-45d4-ae8a-1fcd76ddf18f.png)
> 
> ![image](https://user-images.githubusercontent.com/34127628/135597891-b8d6ef05-3484-40f4-8814-96b026d1a1e7.png)
> 
> 
> 
> A closeup:
> 
> ![image](https://user-images.githubusercontent.com/34127628/135598906-ad1a4b3d-26e2-4be3-972e-c01e850daf9e.png)
> 
> 

Yeah the negative numbers have been there for a while...it's just a minor UI bug that I haven't fixed yet.

**Comment by jeremymuller** [comment]
> Is the gate PW independent from the incoming clock signal? Is it fixed? 
> 
> ![image](https://user-images.githubusercontent.com/34127628/135601171-3a747bbe-1516-4745-adeb-24a46df64d98.png)
> 
> 
> 
> At a moderately high clock speed I see that 'pulses touch each other'. 
> 
> ![image](https://user-images.githubusercontent.com/34127628/135601275-197e2d57-9344-493c-a08a-d9b50807c974.png)
> 
> 

The pulse width is fixed to 0.1 seconds. The VCV Seq3 is set to half the gate length but that has the advantage of its own internal clock. So in this case I just fixed it to a specific time, also like JW-Module sequencers. Does this work ok for you?

**Comment by S0210** [comment]
> > Is the gate PW independent from the incoming clock signal? Is it fixed?
> 
> The pulse width is fixed to 0.1 seconds. The VCV Seq3 is set to half the gate length but that has the advantage of its own internal clock. So in this case I just fixed it to a specific time, also like JW-Module sequencers. Does this work ok for you?

Well, it does work as expected in this case. :)

But I definitely would like to work with shorter PW occasionally. Some basic drum fills (hihat, snare) can't be prepared with a 100ms PW. May I ask you to consider a _Context Menu_ option for _Default Gate Length_ (100ms / 10ms / 2ms)?

It's always easier to make a longer PW (with [this](https://library.vcvrack.com/LittleUtils/PulseGenerator)  or [this](https://library.vcvrack.com/?query=&brand=&tag=Slew+limiter&license=free)) from a trigger than the other way around.

Regards, Andras

**Comment by jeremymuller** [comment]
I originally had the pulse fixed to 0.001 seconds. I can put it back to that, but using an envelope or something like the Vult Trummor for drum sounds I haven't had any issues with staccato notes using the 0.1 seconds gate.

**Comment by S0210** [comment]
I feel really embarrassed to ask; StochSeq4 offers already so much! But having PW at ca. 60ms (0.06s) would add one more neat trick to its menu imho.

**Comment by jeremymuller** [comment]
I see what you mean about how the gate doesn't retrigger drums if it goes too fast. I'll just set it back to 0.001 seconds like I had before. That was never really an issue and is the Rack protocol for pulses. 

If you like these modules please consider sending a donation through paypal or sponsoring this project through github sponsors. Or sharing it with friends that may be able to offer some support. I'd appreciate any help and could dedicate more time and work on Sha#Bang! modules.

**Comment by jeremymuller** [comment]
Thank you for your support! 🙏

**Comment by S0210** [comment]
> Thank you for your support! 🙏

I never used this GitHub feature before. But what better way to start then supporting the best VCV sequencer? ;)

**Comment by jeremymuller** [comment]
I fixed the gates backed to 1 ms and fixed the UI issue of having negative probabilities. It'll be in the next update soon. I could possibly add gate length options, for future updates...if you have any examples of something in mind? I like to try and keep with VCV standards or common practices.

**Comment by jeremymuller** [comment]
Good news! The v2 update is on its way and I included an expander module for StochSeq4 in this commit #39. I think you'll be pleased with it. Rack2 isn't officially released yet but you can find the beta version on the VCV community forum, but you'll need to compile and add any modules you want on your own.

**Comment by S0210** [comment]
The expander works very well. I am even more confident putting StochSeq4 into my patch knowing the option for individual step outputs if needed. Sometimes I leave it there, sometimes I remove it. It's a great addition.

Thank you Jeremy!

<img width="100" alt="image" src="https://user-images.githubusercontent.com/34127628/145533514-3af9b2bd-9660-4b2c-a2ba-2232be66c3f2.png">
