### ISSUE TITLE
Two questions and one request

### ISSUE THREAD

**Issue by nesdnuma** [jeremymuller/Sha-Bang-Modules#3]
Hello,

Cosmosis is a nice module I've just discoverd.

I have two questions:
1. What does the size of  a node represent?
2. How does one change the size.

Also, I have two requests:
1. Is it possible to add a continuous pitch output mode, without any predefined pitch scale?
2. For a polyphonic use, it would be nice that the pitch doesn't reset to 0 when leaving a node but keeps the last value instead.

Thank you in advance.

**Comment by jeremymuller** [comment]
Answers to your questions:
1) In Cosmosis, the size of the star represents pitch only if you have switched the `PITCH` switch to that setting (see manual for more details)
2) Size is set randomly. Each time you click to add a star its radius will be randomly set. There's also a button that will randomize radius and position.

As for your requests, Cosmosis already does what you're asking for:
1) Yes, move the `SCALE` knob all the way clockwise to the right and you will get `Raw Volts` output between 2 octaves. This is the voltage without being quantized to a specific pitch. Also, the `OCTAVES` knobs will still work with raw volts.
2) If I understand you correctly, the pitch doesn't reset to 0. The gate is triggering a pulse and that pulse is reset to 0. Volts/Octave outputs do not change until they are given a different pitch. You can hear this if you attach the V/OCT knob to an oscillator with no envelope.
