### ISSUE TITLE
question on RandGates polyphony limitations

### ISSUE THREAD

**Issue by S0210** [jeremymuller/Sha-Bang-Modules#34]
Dear Jeremy,

I'm experimenting with the polyphonic feature of Rand Gate. I realized that feeding  polyphonic INS and polyphonic TRG I'll get a polyphonic OUT. But only in this case.

Would it be possible to get a polyphonic OUT in case of feeding a polyphonic TRG but _only_ monophonic INS? (It'd mean mixing up the same four notes differently.)

![image](https://user-images.githubusercontent.com/34127628/135802137-af1763bd-c420-468d-ac5a-795e4ad2bc42.png)

It's not impossible even now (see below). But not knowing the complexity of module structure I'm wondering if it can be fixed easily with a few code lines. 

![image](https://user-images.githubusercontent.com/34127628/135803069-1770dabe-e626-4f8b-b855-3aa3d987092a.png)

Cheers, A.

**Comment by jeremymuller** [comment]
I'll take a look at it. I originally just made RandGates to work with PolyrhythmClock where it would randomly select one of the 4 rhythms, which works great for hihats and other percussion stuff.

**Comment by jeremymuller** [comment]
@S0210 I'm trying to figure out what exactly will be the polyphony out from a polyphonic trigger that you're interested in. If it's polyphonic inputs, they get routed to the output and the entire polyphonic signal is sent to the output. However, if all 4. inputs are monophonic but you want a polyphonic out, what exactly will be in the polyphonic signal? Really it's only supposed to be one of four inputs that are outputting at any given time.  So i'm confused about what exactly you want here.

**Comment by S0210** [comment]
To get alternate melodies (with the same four notes) my original suggestion was this

![image](https://user-images.githubusercontent.com/34127628/144985874-d39ef9b0-6d30-403e-8192-168c77713483.png)

TRG input polyphonic
PURPLE input monophonic
BLUE input monophonic
AQUA input monophonic
RED input monophonic
OUT output polyphonic 

Cheers, A.

**Comment by S0210** [comment]
Yes, exactly. Just a small handy feature saving a bunch of cables. :)
