### ISSUE TITLE
SochSeq4 suggestion (Ctrl-LeftClick for entering max/min)

### ISSUE THREAD

**Issue by firolightfog** [jeremymuller/Sha-Bang-Modules#35]
Dear Jeremy,
Would you please consider introducing a new short key (Ctrl-Left-Click) to set probability to 100% (or toggle back to 0%)? 

![image](https://user-images.githubusercontent.com/34127628/136674792-b06e739f-d350-4c99-959d-6eb1e7d5ebf2.png)

It'd tremendously speed up entering triggers and gates by mouse.

Best regards, Andras

**Comment by S0210** [comment]
The more I think the more I prefer inversing the item clicked... 

(I mean 5% -> 95% -> 5% instead of my original suggestion of 5% -> 100% -> 0% -> 100%.)
