### ISSUE TITLE
Stoch Seq4 - Please reset all

### ISSUE THREAD

**Issue by jjdeprisco** [jeremymuller/Sha-Bang-Modules#38]
Love this module!

I noticed that the global reset on Stoch Seq4 does not reset all of the lanes back to the very first segment. In fact, I can't find any pattern to what the global rest actually does.

**Comment by jeremymuller** [comment]
What do you mean global reset? Are you talking about Initialize from the right-click menu? And when you say lanes, are you talking about the current position of each sequence?

**Comment by jjdeprisco** [comment]
Reset each of the 4 sequences to the first position of the sequence. Not initialize. Initialize would destroy any settings you want to use. Already familiar with that.

By lanes I mean each of the 4 discrete sequences... 1, 2, 3, 4 (or as you have them colored, Purple, Dark Blue, Light Blue, and Red)

**Comment by jeremymuller** [comment]
Are you talking about the reset input, labeled as `RST`? It does reset all the sequences to the beginning. You only see it happen on the next clock input.

**Comment by jjdeprisco** [comment]
OK, but that's just not what I am seeing. See video below:

https://youtu.be/K173922iNeg

I would expect a reset trigger to set everything back to the first note of the sequence at the very moment the trigger occurs. What I see here is that the reset, when trigger, moves most of the sequences to the second note of the sequence.

**Comment by jeremymuller** [comment]
Ok I see. That is weird but it looks like you are triggering the `MCLK` as well as all the individual clocks. This is basically like double triggering them, so when you hit reset it gets a double trigger by the two clocks. Have you tried it with only the individual clocks and no `MCLK`?

**Comment by jjdeprisco** [comment]
Yes, I just tried removing the master clock. This image shows the sequencer stopped, then I hit reset on the clock. I would have expected each of the sequences to return to the left-most starting point, but they do not.

![image](https://user-images.githubusercontent.com/35905062/142625527-f341aab4-7231-4761-925b-a18e1f4ed635.png)

**Comment by jeremymuller** [comment]
Ok I'll try to recreate it based on your patch. I have a suspicion as to what the problem is. Are you using Rack v2 yet? All the new updates will go to the `v2` branch of Sha#Bang! now. That branch will eventually be the main branch once Rack v2 is officially released.

**Comment by jjdeprisco** [comment]
This is Rack 1.0. I am not sure when/if I will upgrade to 2.0. My 2015 MacBook Pro sometimes chokes on things with larger patches. My GPU is pretty crappy. My newer 2020 Lenovo does well though, so we'll see. It's also not clear when V2 will be officially released.

But glad the issue is more clear now. I have been using Stoch Step4 for some time and never really noticed this issue because I tend to just let things go from a generative perspective. But in this case I was preparing a lesson for a workshop, and I wanted to be sure I understood what the students were going to see and anticipate questions.

**Comment by Petervos2018** [comment]
@jjdeprisco  The thing that helps is turning off "output resets high when not running" on the clock and change the on start and on stop settings : 

![afbeelding](https://user-images.githubusercontent.com/46076474/142672069-94506158-737f-49f3-9db4-78b565e191ba.png)

It does not reset on stop, but it will play the first segment when you run the clock.

**Comment by Petervos2018** [comment]
Glad you found the way to make it work , and make a video of it.
👍

**Comment by jeremymuller** [comment]
@jjdeprisco wonderful, I'm glad you were able to get it working. I'll still take a look at this weird behavior, although it will be a few days before I can get to it. Thanks for helping out @Petervos2018

**Comment by jeremymuller** [comment]
The way the `MCLK` and individual clocks work at the moment are that the `MCLK` takes priority but doesn't override the individual clocks. In other words, if the individual clocks are getting triggered in between the `MCLK` triggers they will advance the corresponding playheads. 

I was curious if either of you would rather the `MCLK` completely override the individual clocks so that if it is connected the individual clocks won't work at all? I'm considering doing this to prevent any accidental triggers or confusion.

**Comment by jjdeprisco** [comment]
Seems to me the best option would be to provide a switch for both behaviors. Then you have the best of both worlds. There are creative applications for both.

**Comment by S0210** [comment]
I like the way MCLK is working now. But the reset is confusing indeed. Sending a [manual trigger](https://library.vcvrack.com/DHE-Modules/Buttons) to RST it looks rather unreliable:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/34127628/145685329-073ef549-aeab-422f-a1be-4fea17523534.png">

<img width="400" alt="image" src="https://user-images.githubusercontent.com/34127628/145685342-045937bc-79ff-4135-970c-8d5518e23e59.png">

<img width="398" alt="image" src="https://user-images.githubusercontent.com/34127628/145685365-825234f3-ed2e-4926-88cd-f00e6d711935.png">

**Comment by jeremymuller** [comment]
Yeah it seems to be a problem only for the individual clocks if they're going at different rates. That's my next issue to tackle when I get some time.

**Comment by jeremymuller** [comment]
Ok I think I have fixed this issue so be sure to test it out in the next update. Also, @jjdeprisco and @Petervos2018 if you guys are able to help sponsor this project with any amount I would very much appreciate it. Or if you know of others who may be able to help please pass along this message. Thank you!
