### ISSUE TITLE
StochSeq4 Ctrl-arrows in Rack2

### ISSUE THREAD

**Issue by S0210** [jeremymuller/Sha-Bang-Modules#42]
Ctrl-Enter works fine to select the focused sequence (purple, blue, aqua, or red) but the Ctrl-up/down and Ctrl-left/right seems to be disabled.

Best regards, Andras

**Comment by S0210** [comment]
The mouse-click solved my shortcut issue. Thank you! 

I still prefer v1.1.6 to v2.0.2 but the expander is under heavy testing. ;)

**Comment by jeremymuller** [comment]
What is it you like about Rack v1 over v2? Just curious

**Comment by S0210** [comment]
I have all kinds of trouble with Rack v2. :(
- CPU usage is extreme on my primary Win10 laptop with Rack2
- sound quality is crap with Rack2 (probably related to CPU issues)
- Rack2 module browser is almost useless after knowing StoermelderMB/Rack1 
- still missing some of my essential modules (Wiqid, Lindenberg, VCV Prototype)
- booting is way slower with Rack2 for me

![image](https://user-images.githubusercontent.com/34127628/145109887-dea3b04a-cb6d-4b38-97f2-1c98dba8f321.png)

My only drive to Rack2 is a handful of module enhancements (like the ones above). I believe that most of my problems will be fixed by time. But I don't see myself changing permanently for Rack2 for another 6-8 months. 

So if you happen to have too much time to kill, please feel free to introduce any of your simpler modifications to the Rack1 modules too. ;D

**Comment by jeremymuller** [comment]
Oh I see. Well a lot of the modules that may be missing just haven't been ported to v2 yet. So keep checking for that.

Unfortunately there's no way for me to continue working on the Rack v1 library...as far as I can tell. If there were updates to any Rack v1 module you would have to compile it yourself because it looks like the library is only for v2 now.
