### ISSUE TITLE
StochSeq crash in Linux

### ISSUE THREAD

**Issue by jamshark70** [jeremymuller/Sha-Bang-Modules#45]
A student sent me a patch file containing a StochSeq module. Seems to be created in Windows.

When I try to open it in Linux, VCV crashes.

```
[27.824 fatal src/main.cpp:45] Fatal signal 8. Stack trace:
7: ./Rack() [0x56d2b1]
6: /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f1e5ad50210]
5: /home/dlm/.Rack/plugins-v1/Sha-Bang-Modules/plugin.so(_ZN8StochSeq7processERKN4rack6engine6Module11ProcessArgsE+0x4d0) [0x7f1e459d2fc0]
4: ./Rack() [0x5b5da3]
3: ./Rack() [0x5b84af]
2: /lib/x86_64-linux-gnu/libstdc++.so.6(+0xd7172) [0x7f1e5b13f172]
1: /lib/x86_64-linux-gnu/libpthread.so.0(+0x9609) [0x7f1e5bb4a609]
0: /lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7f1e5ae2c293]
```

As another test, I edited the JSON to delete the entire StochSeq node. That version of the file opens without crashing.

This is VCV v1.1.6 btw, Sha#Bang! v1.3.6. (I'm holding off on upgrading to VCV v2 -- it's too near the end of the semester and with students' final projects due, an upgrade would only cause chaos.)

If it matters, the StochSeq contents are:

```
    {
      "id": 52,
      "plugin": "Sha-Bang-Modules",
      "version": "1.3.6",
      "model": "StochSeq",
      "params": [
        {
          "id": 0,
          "value": 0.0
        },
        {
          "id": 1,
          "value": 0.0
        },
        {
          "id": 2,
          "value": 0.0
        },
        {
          "id": 3,
          "value": 0.0
        },
        {
          "id": 4,
          "value": 0.0
        },
        {
          "id": 5,
          "value": 32.0
        },
        {
          "id": 6,
          "value": 1.0
        },
        {
          "id": 7,
          "value": 0.0
        },
        {
          "id": 8,
          "value": 0.0
        }
      ],
      "data": {
        "currentPattern": 0,
        "probs": [
          0.61715591,
          0.228882372,
          0.499028206,
          0.100392938,
          0.740662932,
          0.23050487,
          0.413791656,
          0.320121706,
          0.547417879,
          0.120411992,
          0.797854543,
          0.378019989,
          0.0619246364,
          0.808758378,
          0.464105189,
          0.778698504,
          0.515135288,
          0.192010581,
          0.387599528,
          0.733513951,
          0.361729026,
          0.733513951,
          0.294070721,
          0.776407659,
          0.540452838,
          0.59164083,
          0.693661571,
          0.455613315,
          0.306929708,
          0.0638229251,
          0.540796161,
          0.196885526
        ],
        "percentages": true,
        "kbshortcuts": true
      },
      "pos": [
        0,
        0
      ]
    },
```

**Comment by jeremymuller** [comment]
It doesn't crash on my Mac with those versions, and I assume the student was using Windows and it works fine there? Have you tried loading the StochSeq4 to see if that also crashes it?

Unfortunately the VCV library only has v2 modules (as far as I know). So you'd have to compile an older version of Sha#Bang! if you want them for v1. I'm not sure why it would crash only on Linux though unless it had something to do with the audio driver...but even so I don't think that would be a StochSeq issue. 

Just out of curiosity what class is it that you're teaching? Sounds like it would be a fun class.

**Comment by jamshark70** [comment]
After a little more investigation, I think the cause of the crash is this:

My Linux Rack installation says that all plug-ins are up-to-date, but there is only sha-bang v1.3.3, whereas my student is using v1.3.6.

StochSeq in 1.3.3 has "params" 0 to 7.

StochSeq in 1.3.6 has "params" 0 to 8.

So I think the module constructor, during loading, is trying to write into a parameter for which there's no memory allocated.

So indeed, "wontfix" makes sense. I am curious why the Linux plug-in version lags behind Windows, but it's moot since Rack v2 is out and I will upgrade after grading these exam patches.

(The course is Audio Synthesis Theory, and yes, it's fun :grin: )

**Comment by jeremymuller** [comment]
Awesome, I'm glad you figured it out. Sorry I couldn't be more helpful. But I think you'll like the Rack v2 stuff, although keep in mind that some modules haven't updated yet. You can find more about that from the VCV community forum.
