### ISSUE TITLE
Question on RandRoute polyphony

### ISSUE THREAD

**Issue by S0210** [jeremymuller/Sha-Bang-Modules#46]
Dear Jeremy,

Due to its size and basic parameters the [RandRoute ](https://library.vcvrack.com/Sha-Bang-Modules/RandRoute) became my go-to-Bernoulli-module. I just had a quick question on its polyphony. Is it intentionally delivers the same variation on all output channels? 

<img width="407" alt="image" src="https://user-images.githubusercontent.com/34127628/145731761-1e4dfc5d-70be-4092-b96c-0e932b5969ce.png">

<img width="512" alt="image" src="https://user-images.githubusercontent.com/34127628/145732050-4aef981a-5354-42fe-9977-a80f8a26f913.png">

Best regards, Andras

**Comment by jeremymuller** [comment]
It's a mistake, but should be fixed now.

**Comment by S0210** [comment]
It works perfectly. Thank you!
