### ISSUE TITLE
Question on Photron frame

### ISSUE THREAD

**Issue by S0210** [jeremymuller/Sha-Bang-Modules#49]
Dear Jeremy,

Is the frame a bug or a feature? I usually try to avoid any visual modules so I'm not familiar with their limitations and/or settings. 

<img width="443" alt="image" src="https://user-images.githubusercontent.com/34127628/146238195-f6b5bdfa-a6cd-4b03-9c4a-938775ff7478.png">

Kind regards, Andras

**Comment by jeremymuller** [comment]
That's intentional. Mostly because if the entire thing was lit up in the dim room, it would cover up the knobs and inputs. But I may make some animated changes to that in the future.

**Comment by S0210** [comment]
I see. Thank you!
