### ISSUE TITLE
Proposal for StochSeq4 spread range (-5 to +5)

### ISSUE THREAD

**Issue by S0210** [jeremymuller/Sha-Bang-Modules#50]
Dear Jeremy,

[StochSeq4](https://library.vcvrack.com/Sha-Bang-Modules/StochSeq4) is my use-it-for-all sequencer. Now I rely on it even more than before. Would you please consider changing the SPREAD knob range for -5V to 5V? 

The current range is set to -4V to 4V. The change would increase the compatibility as with a [simple module](https://library.vcvrack.com/JW-Modules/Add5) any sequence could be transformed to 0V to 10V if needed. Or with another [simple module](https://library.vcvrack.com/DHE-Modules/Func) the voltage could be multiplied and transformed to a -10V to +10V.

Best regards, Andras

P.S.: Actually I'm not sure that negative values makes sense at all. We have access to the INV output anyway if needed without manually turning the SPREAD from +2 to -2.

**Comment by jeremymuller** [comment]
Sure thing, I can change the range to ±5V. I originally had negative values before I added the `INV` output. But yeah I can't really see a need for it now, seems kinda redundant. Maybe I should actually change them to 0-5V or 0-10V?

**Comment by S0210** [comment]
I'd clearly vote for the 0-10V range then. Cheers, A.
