### ISSUE TITLE
Proposal on PolyRhythm labelling tuplet 2&3

### ISSUE THREAD

**Issue by firolightfog** [jeremymuller/Sha-Bang-Modules#52]
Dear Jeremy,

I'd like to propose a change for your consideration. It is related to the **ratio labels** of TUPLET 2 and TUPLET 3. 

In my example both the left (current) and right (proposed) modules **show 2:1 in the blue** section. The left (current) module **shows 3:1 in the aqua section** meaning that the tempo of blue is triplicated. But the right (proposed) module would **show 6:1 in the aqua section** meaning the same thing but referring to the ratio of the master BPM. 

Just to clarify, the behavior of the two modules in my example are the same otherwise: The voltage outputs and knob settings of the two modules are exactly the same. It's just that trying to explain multiple times the way the module works I feel that the proposed labelling would reduce learning time. 

![image](https://user-images.githubusercontent.com/34127628/147404218-d44259ce-9939-42de-a26c-fbd5242abd86.png)

Best regards, Andras

**Comment by jeremymuller** [comment]
The original idea of that clock is to create layers of embedded polyrhythms. This is inspired by people like Brian Ferneyhough, Frank Zappa, Stuart Saunders Smith, et al. So each rhythm is based on a parent rhythm. Most clocks already do basic multiplication or division but they don't do multiple layers beyond that. That was also a motivation for creating the Polyrhythm Clock and makes it unique. And you can essentially create any fractional rhythm you can think of. 

I could make a separate clock module if you're interested...I actually had an idea for one already.

**Comment by S0210** [comment]
I'm more than happy with the completely crazy 'nested' polyrhythms the module can generate. It is unique in its own way. I just thought that a different labelling would help easier understanding. 

The rhythm is calculated anyway based on the master BPM (purple). In my test below I can see that reducing the blue probability doesn't have an impact on the aqua output. So aqua output can be considered more like a 4:1 ration of the master BPM (purple) than 2:1 ratio of blue BPM. I think that the proposed labelling wouldn't be misleading.
<img width="366" alt="image" src="https://user-images.githubusercontent.com/34127628/147414038-8d776d97-335c-4647-8cf5-4cf0c4429d56.png">

But obviously once the blue ratio is set to 2:1 the aqua knob could select only 2:1, 4:1, 6:1, 8:1 etc labels. (Same tempo currently represented as aqua 1:1, 2:1, 3:1, 4:1.) The proposal is really only about the labels. 

However I'm enthusiastic knowing that you are considering a new master clock module. I'd love to replace [Clocked](https://library.vcvrack.com/ImpromptuModular/Clocked) with one of your no-nonsense modules. [I know for fact ](https://www.youtube.com/watch?v=Csx3Xe8h1lM) that you have the right mindset for a proper clock module. Just let me know if you'd like to hear a few completely incompetent comments. 

Regards, Andras

**Comment by jeremymuller** [comment]
Ah ok, I see. I think I misunderstood you in thinking you wanted to change the embedded part of the rhythms. Yeah maybe changing the labeling would be ok, or adding it as a menu option. However, the problem is that if I had the clock set to 60 bpm, tuplet 1 set to 3:1, and tuplet 2 set to 7:5, it wouldn't make much sense what tuplet 2 is doing against the main clock (60 bpm). So if someone is wanting to do complex rhythms like that they only really make sense in the context of being embedded. 

Thanks for your kind comments. Your suggestions are very helpful, too. It helps to get an outside perspective on how these modules are being used and how they can be improved.
