### ISSUE TITLE
Proposal on StochSeq column colors

### ISSUE THREAD

**Issue by S0210** [jeremymuller/Sha-Bang-Modules#53]
Dear Jeremy,

Please don't consider this ticket as a proper feature request. It's more like pondering about potential improvements. 

I'm wondering if it'd be worth the hassle to implement a Ctrl-right-click option for some basic column colors?

Again I don't know how much coding is needed but I mean something like this. (Please ignore the module on the right for now.)

<img width="312" alt="image" src="https://user-images.githubusercontent.com/34127628/148509953-c6928917-8ef4-4ebd-af7f-4f6a0f1788d2.png">

Best regards, Andras

**Comment by jeremymuller** [comment]
I'll look into it but I'm not sure how feasible this will be since there's already a context menu.

**Comment by S0210** [comment]
Dear Jeremy,

I withdraw my proposal. 

I was making a lot of drawings, thinking about the colors, the use cases and the benefits. Practically it makes no sense. So regardless the coding challenges it may provide I suggest to drop the idea.

Best regards, Andras
