### ISSUE TITLE
Question on RandGates (w/o TRG)

### ISSUE THREAD

**Issue by S0210** [jeremymuller/Sha-Bang-Modules#54]
Dear Jeremy,

What does RandGates do without a TRG? Is it an OR module?

<img width="205" alt="image" src="https://user-images.githubusercontent.com/34127628/148737334-edfe73a9-5c07-48aa-82ea-42b324607dd8.png">

Somehow I expected that if no cable is connected to TRG then another IN will be selected once the currently active signal drops below 2V.  But it's clearly something else.

Best regards, Andras

**Comment by Petervos2018** [comment]
You chose a "weird" divider/multiplier, the catro modulo does this : 

The left column outputs multiply the incoming signal, so you get 10V 20V 30V etc.

The right column outputs multiply the clock/gate and output 1 x 2 x 3 x when the clock/gate is high or 0 when low. ( the number of gates out depend on the bpm, (it's a strange module)

So what you see is just the output of the blue input.

**Comment by S0210** [comment]
You are right.

<img width="304" alt="image" src="https://user-images.githubusercontent.com/34127628/148765020-473d8cef-02f2-4230-989c-1064ab21e87f.png">

**Comment by jeremymuller** [comment]
Yeah it just outputs the most recent input that was randomly chosen last time it was triggered.
