### ISSUE TITLE
Stochastic Sequencer 4 instance is not sending any v/oct

### ISSUE THREAD

**Issue by spectromas** [jeremymuller/Sha-Bang-Modules#58]
Just reopened a patch from a few weeks ago and the sequencer is not sending any voltage on the v/oct outputs. I've got a few proprietary modules but I think as long as you have ZZC modules installed then it should be enough, just check the scope. 

[plethora.zip](https://github.com/jeremymuller/Sha-Bang-Modules/files/7997430/plethora.zip)
 

I might be missing something really basic but I can't figure out why nothing is coming out of it.

Edit: just opened another patch and the same thing is happening.

**Comment by jeremymuller** [comment]
You likely need to reset the V/OCT mode. If you just did the latest update then some of your previous data might be setting it to an incorrect value. 

Did you try this?

![Screen Shot 2022-02-03 at 2 19 28 PM](https://user-images.githubusercontent.com/8097236/152413841-3a617b58-ae48-4b8e-b2cf-be8b5c705999.png)

**Comment by spectromas** [comment]
That does produce some output. Did something change with the ranges and octaves? The notes being played now have a far higher range than they did.

**Comment by jeremymuller** [comment]
Yes you use the right click menu to set the volt range and the knob as a percentage of that range.

**Comment by spectromas** [comment]
I did change it but the voltage ranges are still much larger than they were and it doesn't seem possible to get back to what it was previously without changing the scale which is a lottery in terms of getting the range that was previously saved.

**Comment by jeremymuller** [comment]
Could you give me a screenshot of what you have? It shouldn't be difficult to get the desired range. For example, if you want 1 octave you would set the range to 10 volts and turn the knob to 10%. I think there's also a 1V range too (I'm unable to check it for sure right now)

**Comment by spectromas** [comment]
Sure, this is another patch. I don't know what the settings were before but it's currently playing with several extra octaves than it did. 
![Screenshot_20220203_220706](https://user-images.githubusercontent.com/6443372/152437353-a34d8bfc-5f51-42f5-b512-9690d323543f.png)

**Comment by S0210** [comment]
In previous version the knob range was -4 to +4.  So your 74% should mean ca. 1 in the old version. That should be 1 octave I think. So setting selecting 10V (Volt Offset) and set the knob 10% sounds like a good idea.

**Comment by spectromas** [comment]
That does sound much more in line to how it should be. Some of the settings are not exact though, one is 74.12, another is 76.63, and another is 54.69. Is there some maths to convert it accurately? Is there no way of making whatever the change was backwards compatible? It breaks many patches as it is now.

**Comment by jeremymuller** [comment]
There's no way to make it backwards compatible unless you just compile it on your own. I suppose there may be some hacky way around it but I just don't have the time or resources to do it.

You could try this formula to convert it to what it is now: 
- x / 100 * 8 - 4, x = current knob value
- Set your V/OCT offset to ±5V
- multiply the formula result by 20

That should give you the same V/OCT (I think)
