### ISSUE TITLE
has stochseq4 and stoch seq an error?

### ISSUE THREAD

**Issue by socratesru** [jeremymuller/Sha-Bang-Modules#63]
I need some help, im getting into this magnificent sequencer but i cant fully understand how it works, ive already seen the creators official tutorial and i notice that it doesnt work the same for me, when i put the probability at 100%  in the entire sequence it doesnt send a constant gate signal, it just gets stuck there, what happens, what im doing wrong?

It should be noted that the version I have of the modules is 2.1.0, the same error happens with stochseq4 and  stoch seq

[https://youtu.be/hCwd3-W0bDo](url)

**Comment by Petervos2018** [comment]
Hi ,

A gate is either open (high) or closed (low). When you follow a high gate with a low one the voltage goes from high to low.

When you follow a high gate with a high one the voltage stays high and there is no change in the signal.

When you set all the gates to high you just create one high signal.

So this is not an error.

**Comment by socratesru** [comment]
> Hi ,
> 
> A gate is either open (high) or closed (low). When you follow a high gate with a low one the voltage goes from high to low.
> 
> When you follow a high gate with a high one the voltage stays high and there is no change in the signal.
> 
> When you set all the gates to high you just create one high signal.
> 
> So this is not an error.

friend in the official tutorial I see clearly when the user leaves all the probabilities at 100% constantly sends a gate signal, look at the official video and you will realize

[https://youtu.be/LBL_VYe_stU?t=244](url)

**Comment by Petervos2018** [comment]
Right-click the module and set gates to triggers : 

![afbeelding](https://user-images.githubusercontent.com/46076474/156434889-7dc5c547-a4b3-4b4a-b5c0-9439ee24fa9b.png)

**Comment by socratesru** [comment]
> Right-click the module and set gates to triggers :
> 
> ![afbeelding](https://user-images.githubusercontent.com/46076474/156434889-7dc5c547-a4b3-4b4a-b5c0-9439ee24fa9b.png)
> 
> Just trying to help, but maybe I don't understand your problem.

Thank you very much, it was definitely me who was wrong, it is as you say changing the gate for trigger, now I can start using these sequencers correctly, again thank you very much

**Comment by jeremymuller** [comment]
Thanks for helping with this @Petervos2018.
