### ISSUE TITLE
These modules don't build for me without modifying the makefile

### ISSUE THREAD

**Issue by squinkylabs** [jeremymuller/Sha-Bang-Modules#64]
first line:
\# If RACK_DIR is not defined when calling the Makefile, default to two directories above
RACK_DIR ?= ../

most ppl use `../..` with four dots. Then the makefile matches the comment. Anyway `make` didn't make for me until I modified the makefile to be like all the other ones.

**Comment by jeremymuller** [comment]
Yeah i know, I changed that on purpose to work with my setup. And it works fine when it's compiled and added to the VCV library because I assume they're using their own makefile. Does it still work ok for you?

**Comment by squinkylabs** [comment]
It works fine for me, once I edit it to me like other modules.
