### ISSUE TITLE
Photron Strip's Strip mode pulse rate doesn't save

### ISSUE THREAD

**Issue by flarn2006** [jeremymuller/Sha-Bang-Modules#66]
When I set a Photron Strip's mode to "solid color" or "strip", I can change the pulse rate and hue from the menu. However, if I reload a saved file, the pulse rate is reset to 0.5 Hz, even if it was set to something different when the file was saved. This issue only applies to the pulse rate, not the hue.

**Comment by jeremymuller** [comment]
Ok that's something I overlooked. I'll fix it in the next update.

**Comment by flarn2006** [comment]
Figured that was an oversight—no worries!

**Comment by scheichreisuli** [comment]
Hello,

an additional advice:

when saving a setting as "default", this is ignored the next time VCV is started again or a new instance of the module is added to the patch.

Cheers
