### ISSUE TITLE
Clock to Cosmosis sequencer suggestion

### ISSUE THREAD

**Issue by vcvrackideas** [jeremymuller/Sha-Bang-Modules#68]
Hi Jeremy! Your sequencer just does incredible stuff, thanks! example here - https://youtu.be/RNj7_CT9f4A
Could you please add a clock input? for using this one not only in ambient patches. Or could it be synced with BPM CV output from Impromptu CLOCK? 
Cheers!

**Comment by jeremymuller** [comment]
Well this is a continuous (non-discrete) sequencer, so it doesn't make much sense to "sync" with a clock. There's a play input and a speed input for external controls, but it's not meant to be grid sequencer, it's more for rhythms or textures in the cracks.
