### ISSUE TITLE
Neutrinode request(s)

### ISSUE THREAD

**Issue by bakman2** [jeremymuller/Sha-Bang-Modules#7]
Hi, neutrino is truly awesome, hook it up to a fm-op and some reverb and it can play all day ;) Thank you so much, donation is on its way.

I have some request for this module, if feasible/possible.

- a collision detect option for the balls when they are moving - if they overlap eachother it can become "messy" (exaggeratation) as they could play notes almost together but just too short apart. Some kind of collision detect (or even that they bounce of eachother).
- cv input for the root (perhaps also for the octaves), i can map them with umap so not a big deal, but nice to have.

**Comment by jeremymuller** [comment]
Hi @bakman2, thank you :pray: :pray: :pray:

I appreciate your donation and so glad you like Neutrinode. I definitely like using it with some reverb and/or slow delays. I'll work on adding a collision so they bounce off each other. And a CV input to control the root note is already on my TODO list.

**Comment by jeremymuller** [comment]
Will be in the next update whenever VCV Rack manager do the next update build, probably in a few days.

**Comment by bakman2** [comment]
Thanks a lot!
