### ISSUE TITLE
Polyrhythm Clock FR: Add Run toggle input

### ISSUE THREAD

**Issue by fractalgee** [jeremymuller/Sha-Bang-Modules#70]
I usually sync it from Clocked and would be good to have Clocked also turn on and off clock when it is turned on and off via it's Run output. A bit troublesome that the clock stays running even when external sync clock is turned off.

Great module otherwise! Thanks for these.

**Comment by jeremymuller** [comment]
The clock will turn off automatically after a certain timeout period from not receiving any more pulses.
