### ISSUE TITLE
FR: make Polyrythm clock sync to external clock.

### ISSUE THREAD

**Issue by Torinbob** [jeremymuller/Sha-Bang-Modules#8]
Hi,

I'm really enjoying your polyrythm clock, however I think it would be more useful if it could be externally synced to another master clock like Impromptu Clocked and the ZZC clock for example, ideally at 24 ppqn.

While the Polyrythm clock is great for polyrhythms, imo it is missing many features that would enable it to step into the master clock role (in my setup at least) so having it being able to sync to a separate master clock would make it much more usable and able to fit into existing templates.

thanks

**Comment by jeremymuller** [comment]
Thanks for the suggestions, I'll add it to the TODO list.

**Comment by jeremymuller** [comment]
Ok, looking at the Impromptu Clocks and I also like the CV input where you can change the BPM based on a pitch. I'm working on adding an external clock input to my PolyrhythmClock and I'll get this out with the next small update. 

I'm also thinking about making an additional module with an expanded version of the PolyrhythmClock. That may come out in the next large update (I have other modules I'm working on adding to this plugin as well).

**Comment by Torinbob** [comment]
Excellent - thank you very much for implementing the external clock, I look forward to trying it.

**Comment by jeremymuller** [comment]
This will appear in the next update of the plugin
